# Generated by Django 4.2.27 on 2025-12-31 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA256 hash of the file', max_length=128)),
                ('ingestion_type', models.CharField(choices=[('Postgres', 'PostgreSQL'), ('S3', 'S3 Upload')], db_index=True, default='Postgres', help_text='Type of ingestion (Postgres or S3)', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', help_text='Current status of the job', max_length=32)),
                ('table_name', models.CharField(blank=True, help_text='Name of the database table created/updated', max_length=128, null=True)),
                ('inserted_count', models.IntegerField(blank=True, help_text='Number of rows inserted or file size in bytes', null=True)),
                ('file_names', models.TextField(blank=True, help_text='JSON string of file names (for multiple files) or single filename', null=True)),
                ('file_count', models.IntegerField(blank=True, help_text='Number of files processed (for directory uploads)', null=True)),
                ('message', models.TextField(blank=True, help_text='Status message or error description', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Job creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash', 'ingestion_type'], name='jobs_file_ha_b001f3_idx'), models.Index(fields=['status', 'created_at'], name='jobs_status_24a2b0_idx'), models.Index(fields=['ingestion_type', 'status'], name='jobs_ingesti_8a93b1_idx')],
            },
        ),
    ]
